# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./autogen/B2.mk ./autogen/B2.urp
./autogen/B2.urp: ./autogen/B2.mk .cake3/tmpB2.in0 autogen/B2_css.ur autogen/B2_css.urs autogen/B2_css_c.h autogen/B2_css_c.o
	cat .cake3/tmpB2.in0 > ./autogen/B2.urp
.cake3/tmpB2.in0: ./autogen/B2.mk
	-rm -rf .cake3/tmpB2.in0
	echo 'include ../autogen/B2_css_c.h' >> .cake3/tmpB2.in0
	echo 'link ../autogen/B2_css_c.o' >> .cake3/tmpB2.in0
	echo 'ffi ../autogen/B2_css_c' >> .cake3/tmpB2.in0
	echo 'ffi ../autogen/B2_css_js' >> .cake3/tmpB2.in0
	echo 'allow mime text/css' >> .cake3/tmpB2.in0
	echo 'safeGet B2_css/blobpage' >> .cake3/tmpB2.in0
	echo 'safeGet B2_css/blob' >> .cake3/tmpB2.in0
	echo '' >> .cake3/tmpB2.in0
	echo '../autogen/B2_css' >> .cake3/tmpB2.in0
autogen/B2_css_c.o: ./autogen/B2.mk autogen/B2_css_c.c $(call GUARD,URCC) $(call GUARD,URINCL) $(call GUARD,UR_CFLAGS)
	$(URCC) -c $(URINCL) $(UR_CFLAGS)  -o autogen/B2_css_c.o autogen/B2_css_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,UR_CFLAGS):
	rm -f .cake3/GUARD_UR_CFLAGS_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./autogen/B2.urp
./autogen/B2.urp: .fix-multy1
.PHONY: .cake3/tmpB2.in0
.cake3/tmpB2.in0: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./autogen/B2.mk $(MAKECMDGOALS)
.PHONY: autogen/B2_css_c.o
autogen/B2_css_c.o: .fix-multy1

endif
.PHONY: clean
clean: 
	-rm ./autogen/B2.urp .cake3/tmpB2.in0 autogen/B2_css_c.o
	-rm -rf .cake3

endif
