# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./autogen/holder.mk ./autogen/holder.urp
./autogen/holder.urp: ./autogen/holder.mk .cake3/tmpholder.in0 autogen/Holder_js.ur autogen/Holder_js.urs autogen/Holder_js_c.h autogen/Holder_js_c.o
	cat .cake3/tmpholder.in0 > ./autogen/holder.urp
.cake3/tmpholder.in0: ./autogen/holder.mk
	-rm -rf .cake3/tmpholder.in0
	echo 'include ../autogen/Holder_js_c.h' >> .cake3/tmpholder.in0
	echo 'link ../autogen/Holder_js_c.o' >> .cake3/tmpholder.in0
	echo 'ffi ../autogen/Holder_js_c' >> .cake3/tmpholder.in0
	echo 'ffi ../autogen/Holder_js_js' >> .cake3/tmpholder.in0
	echo 'allow mime text/javascript' >> .cake3/tmpholder.in0
	echo 'safeGet Holder_js/blobpage' >> .cake3/tmpholder.in0
	echo 'safeGet Holder_js/blob' >> .cake3/tmpholder.in0
	echo '' >> .cake3/tmpholder.in0
	echo '../autogen/Holder_js' >> .cake3/tmpholder.in0
autogen/Holder_js_c.o: ./autogen/holder.mk autogen/Holder_js_c.c $(call GUARD,URCC) $(call GUARD,URINCL) $(call GUARD,UR_CFLAGS)
	$(URCC) -c $(URINCL) $(UR_CFLAGS)  -o autogen/Holder_js_c.o autogen/Holder_js_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,UR_CFLAGS):
	rm -f .cake3/GUARD_UR_CFLAGS_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./autogen/holder.urp
./autogen/holder.urp: .fix-multy1
.PHONY: .cake3/tmpholder.in0
.cake3/tmpholder.in0: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./autogen/holder.mk $(MAKECMDGOALS)
.PHONY: autogen/Holder_js_c.o
autogen/Holder_js_c.o: .fix-multy1

endif
.PHONY: clean
clean: 
	-rm ./autogen/holder.urp .cake3/tmpholder.in0 autogen/Holder_js_c.o
	-rm -rf .cake3

endif
